backend: openai
base_url: http://localhost:8000/v1
api_key: dummy
model: /public/lianghong/nurdaulet_absattarov/train_qwen/saves/sft_merged
params:
 temperature: 0.0
 max_completion_tokens: 32768
thinking: false
